@echo off
echo Starting Visora Web Interface...
echo Make sure you have installed the requirements first: pip install -r requirements.txt
echo.
echo Opening web browser...
start http://localhost:8501
echo Starting Streamlit application...
python -m streamlit run app/web_interface.py